//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ProductService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="BAS.ServiceModel", ConfigurationName="ProductService.ProductsService")]
    public interface ProductsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Create", ReplyAction="BAS.ServiceModel/BaseService/CreateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.Product>))]
        System.ValueTuple<bool, object> Create(BAS.DataModelLibrary.Product parametr);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Create", ReplyAction="BAS.ServiceModel/BaseService/CreateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(BAS.DataModelLibrary.Product parametr);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Update", ReplyAction="BAS.ServiceModel/BaseService/UpdateResponse")]
        System.ValueTuple<bool, string> Update(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Update", ReplyAction="BAS.ServiceModel/BaseService/UpdateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Delete", ReplyAction="BAS.ServiceModel/BaseService/DeleteResponse")]
        System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Delete", ReplyAction="BAS.ServiceModel/BaseService/DeleteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetAll", ReplyAction="BAS.ServiceModel/BaseService/GetAllResponse")]
        System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetAll", ReplyAction="BAS.ServiceModel/BaseService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetBy", ReplyAction="BAS.ServiceModel/BaseService/GetByResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.Product>))]
        System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetBy(string fieldName, object parametr);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetBy", ReplyAction="BAS.ServiceModel/BaseService/GetByResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetByAsync(string fieldName, object parametr);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/ProductsService/GetByPrice", ReplyAction="BAS.ServiceModel/ProductsService/GetByPriceResponse")]
        System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetByPrice(int minprice, System.Nullable<int> maxprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/ProductsService/GetByPrice", ReplyAction="BAS.ServiceModel/ProductsService/GetByPriceResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetByPriceAsync(int minprice, System.Nullable<int> maxprice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsServiceChannel : TestService.ProductService.ProductsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceClient : System.ServiceModel.ClientBase<TestService.ProductService.ProductsService>, TestService.ProductService.ProductsService {
        
        public ProductsServiceClient() {
        }
        
        public ProductsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<bool, object> Create(BAS.DataModelLibrary.Product parametr) {
            return base.Channel.Create(parametr);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(BAS.DataModelLibrary.Product parametr) {
            return base.Channel.CreateAsync(parametr);
        }
        
        public System.ValueTuple<bool, string> Update(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs) {
            return base.Channel.Update(parametrs);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs) {
            return base.Channel.UpdateAsync(parametrs);
        }
        
        public System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs) {
            return base.Channel.Delete(parametrs);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Product> parametrs) {
            return base.Channel.DeleteAsync(parametrs);
        }
        
        public System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetBy(string fieldName, object parametr) {
            return base.Channel.GetBy(fieldName, parametr);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetByAsync(string fieldName, object parametr) {
            return base.Channel.GetByAsync(fieldName, parametr);
        }
        
        public System.Collections.Generic.List<BAS.DataModelLibrary.Product> GetByPrice(int minprice, System.Nullable<int> maxprice) {
            return base.Channel.GetByPrice(minprice, maxprice);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Product>> GetByPriceAsync(int minprice, System.Nullable<int> maxprice) {
            return base.Channel.GetByPriceAsync(minprice, maxprice);
        }
    }
}
