//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="BAS.ServiceModel", ConfigurationName="ServiceReference1.OrdersService")]
    public interface OrdersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Create", ReplyAction="BAS.ServiceModel/BaseService/CreateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.DeliveriService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.OrderedProduct>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.OrderedProduct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.OrderStatus>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.OrderStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        System.ValueTuple<bool, object> Create(BAS.DataModelLibrary.Order parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Create", ReplyAction="BAS.ServiceModel/BaseService/CreateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(BAS.DataModelLibrary.Order parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Update", ReplyAction="BAS.ServiceModel/BaseService/UpdateResponse")]
        System.ValueTuple<bool, string> Update(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Update", ReplyAction="BAS.ServiceModel/BaseService/UpdateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Delete", ReplyAction="BAS.ServiceModel/BaseService/DeleteResponse")]
        System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/Delete", ReplyAction="BAS.ServiceModel/BaseService/DeleteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetAll", ReplyAction="BAS.ServiceModel/BaseService/GetAllResponse")]
        System.Collections.Generic.List<BAS.DataModelLibrary.Order> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetAll", ReplyAction="BAS.ServiceModel/BaseService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Order>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetBy", ReplyAction="BAS.ServiceModel/BaseService/GetByResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.DeliveriService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.OrderedProduct>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.OrderedProduct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.OrderStatus>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.OrderStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.DataModelLibrary.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.DataModelLibrary.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        System.Collections.Generic.List<BAS.DataModelLibrary.Order> GetBy(string fieldName, object parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="BAS.ServiceModel/BaseService/GetBy", ReplyAction="BAS.ServiceModel/BaseService/GetByResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Order>> GetByAsync(string fieldName, object parameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersServiceChannel : TestService.ServiceReference1.OrdersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceClient : System.ServiceModel.ClientBase<TestService.ServiceReference1.OrdersService>, TestService.ServiceReference1.OrdersService {
        
        public OrdersServiceClient() {
        }
        
        public OrdersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<bool, object> Create(BAS.DataModelLibrary.Order parameter) {
            return base.Channel.Create(parameter);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(BAS.DataModelLibrary.Order parameter) {
            return base.Channel.CreateAsync(parameter);
        }
        
        public System.ValueTuple<bool, string> Update(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters) {
            return base.Channel.Update(parameters);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters) {
            return base.Channel.UpdateAsync(parameters);
        }
        
        public System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters) {
            return base.Channel.Delete(parameters);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<BAS.DataModelLibrary.Order> parameters) {
            return base.Channel.DeleteAsync(parameters);
        }
        
        public System.Collections.Generic.List<BAS.DataModelLibrary.Order> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Order>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.Collections.Generic.List<BAS.DataModelLibrary.Order> GetBy(string fieldName, object parameter) {
            return base.Channel.GetBy(fieldName, parameter);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.DataModelLibrary.Order>> GetByAsync(string fieldName, object parameter) {
            return base.Channel.GetByAsync(fieldName, parameter);
        }
    }
}
