//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.27703.1
// 
namespace BAS.OrderService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class Order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CommentField;
        
        private System.DateTime DateOrderField;
        
        private BAS.OrderService.DeliveriService DeliveryServiceField;
        
        private System.Nullable<int> IdField;
        
        private BAS.OrderService.Customer OrderCustomerField;
        
        private System.Collections.Generic.List<BAS.OrderService.OrderedProduct> OrderListField;
        
        private System.Collections.Generic.List<BAS.OrderService.OrderStatus> OrderStatusesField;
        
        private long TotalSumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOrder {
            get {
                return this.DateOrderField;
            }
            set {
                if ((this.DateOrderField.Equals(value) != true)) {
                    this.DateOrderField = value;
                    this.RaisePropertyChanged("DateOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BAS.OrderService.DeliveriService DeliveryService {
            get {
                return this.DeliveryServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryServiceField, value) != true)) {
                    this.DeliveryServiceField = value;
                    this.RaisePropertyChanged("DeliveryService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BAS.OrderService.Customer OrderCustomer {
            get {
                return this.OrderCustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCustomerField, value) != true)) {
                    this.OrderCustomerField = value;
                    this.RaisePropertyChanged("OrderCustomer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BAS.OrderService.OrderedProduct> OrderList {
            get {
                return this.OrderListField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderListField, value) != true)) {
                    this.OrderListField = value;
                    this.RaisePropertyChanged("OrderList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BAS.OrderService.OrderStatus> OrderStatuses {
            get {
                return this.OrderStatusesField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusesField, value) != true)) {
                    this.OrderStatusesField = value;
                    this.RaisePropertyChanged("OrderStatuses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalSum {
            get {
                return this.TotalSumField;
            }
            set {
                if ((this.TotalSumField.Equals(value) != true)) {
                    this.TotalSumField = value;
                    this.RaisePropertyChanged("TotalSum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveriService", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class DeliveriService : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string ServiceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ushort AgeField;
        
        private string CustomerAddressField;
        
        private string EmailField;
        
        private string FNameField;
        
        private System.Nullable<int> IdField;
        
        private string LNameField;
        
        private string MNameField;
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderedProduct", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class OrderedProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAS.OrderService.Product ProductField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BAS.OrderService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class OrderStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime DateChangeField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateChange {
            get {
                return this.DateChangeField;
            }
            set {
                if ((this.DateChangeField.Equals(value) != true)) {
                    this.DateChangeField = value;
                    this.RaisePropertyChanged("DateChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/DataModelLibrary")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> ArticulusField;
        
        private string ColorField;
        
        private string DescriptionField;
        
        private string ManufacturerField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private uint QuantityField;
        
        private System.Nullable<ushort> SaleField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Articulus {
            get {
                return this.ArticulusField;
            }
            set {
                if ((this.ArticulusField.Equals(value) != true)) {
                    this.ArticulusField = value;
                    this.RaisePropertyChanged("Articulus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ushort> Sale {
            get {
                return this.SaleField;
            }
            set {
                if ((this.SaleField.Equals(value) != true)) {
                    this.SaleField = value;
                    this.RaisePropertyChanged("Sale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfbooleananyType", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.DeliveriService))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.OrderedProduct>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.OrderedProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.OrderStatus>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.OrderStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.Order>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BAS.OrderService.ValueTupleOfbooleanstring))]
    public partial struct ValueTupleOfbooleananyType : System.ComponentModel.INotifyPropertyChanged {
        
        private bool Item1Field;
        
        private object Item2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((this.Item1Field.Equals(value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValueTupleOfbooleanstring", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct ValueTupleOfbooleanstring : System.ComponentModel.INotifyPropertyChanged {
        
        private bool Item1Field;
        
        private string Item2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Item1 {
            get {
                return this.Item1Field;
            }
            set {
                if ((this.Item1Field.Equals(value) != true)) {
                    this.Item1Field = value;
                    this.RaisePropertyChanged("Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Item2 {
            get {
                return this.Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Item2Field, value) != true)) {
                    this.Item2Field = value;
                    this.RaisePropertyChanged("Item2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ServiceModel", ConfigurationName="OrderService.OrdersService")]
    public interface OrdersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Create", ReplyAction="ServiceModel/BaseService/CreateResponse")]
        System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleananyType> CreateAsync(BAS.OrderService.Order parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Update", ReplyAction="ServiceModel/BaseService/UpdateResponse")]
        System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleanstring> UpdateAsync(System.Collections.Generic.List<BAS.OrderService.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Delete", ReplyAction="ServiceModel/BaseService/DeleteResponse")]
        System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleanstring> DeleteAsync(System.Collections.Generic.List<BAS.OrderService.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetAll", ReplyAction="ServiceModel/BaseService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetFromTo", ReplyAction="ServiceModel/BaseService/GetFromToResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetFromToAsync(uint from, uint to);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetBy", ReplyAction="ServiceModel/BaseService/GetByResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.DeliveriService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.OrderedProduct>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.OrderedProduct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.OrderStatus>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.OrderStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<BAS.OrderService.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.ValueTupleOfbooleananyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BAS.OrderService.ValueTupleOfbooleanstring))]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetByAsync(string fieldName, object value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersServiceChannel : BAS.OrderService.OrdersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceClient : System.ServiceModel.ClientBase<BAS.OrderService.OrdersService>, BAS.OrderService.OrdersService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrdersServiceClient() : 
                base(OrdersServiceClient.GetDefaultBinding(), OrdersServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_OrdersService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdersServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OrdersServiceClient.GetBindingForEndpoint(endpointConfiguration), OrdersServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdersServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrdersServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdersServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrdersServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrdersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleananyType> CreateAsync(BAS.OrderService.Order parameter) {
            return base.Channel.CreateAsync(parameter);
        }
        
        public System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleanstring> UpdateAsync(System.Collections.Generic.List<BAS.OrderService.Order> parameters) {
            return base.Channel.UpdateAsync(parameters);
        }
        
        public System.Threading.Tasks.Task<BAS.OrderService.ValueTupleOfbooleanstring> DeleteAsync(System.Collections.Generic.List<BAS.OrderService.Order> parameters) {
            return base.Channel.DeleteAsync(parameters);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetFromToAsync(uint from, uint to) {
            return base.Channel.GetFromToAsync(from, to);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BAS.OrderService.Order>> GetByAsync(string fieldName, object value) {
            return base.Channel.GetByAsync(fieldName, value);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_OrdersService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_OrdersService)) {
                return new System.ServiceModel.EndpointAddress("http://93.157.234.12/api/OrdersService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return OrdersServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_OrdersService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return OrdersServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_OrdersService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_OrdersService,
        }
    }
}
