//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestService.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ServiceModel", ConfigurationName="OrderService.OrdersService")]
    public interface OrdersService {
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Create", ReplyAction="ServiceModel/BaseService/CreateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.DeliveriService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.OrderedProduct>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.OrderedProduct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.OrderStatus>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.OrderStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        System.ValueTuple<bool, object> Create(DataModelLibrary.Order parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Create", ReplyAction="ServiceModel/BaseService/CreateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(DataModelLibrary.Order parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Update", ReplyAction="ServiceModel/BaseService/UpdateResponse")]
        System.ValueTuple<bool, string> Update(System.Collections.Generic.List<DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Update", ReplyAction="ServiceModel/BaseService/UpdateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Delete", ReplyAction="ServiceModel/BaseService/DeleteResponse")]
        System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/Delete", ReplyAction="ServiceModel/BaseService/DeleteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<DataModelLibrary.Order> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetAll", ReplyAction="ServiceModel/BaseService/GetAllResponse")]
        System.Collections.Generic.List<DataModelLibrary.Order> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetAll", ReplyAction="ServiceModel/BaseService/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetFromTo", ReplyAction="ServiceModel/BaseService/GetFromToResponse")]
        System.Collections.Generic.List<DataModelLibrary.Order> GetFromTo(uint from, uint to);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetFromTo", ReplyAction="ServiceModel/BaseService/GetFromToResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetFromToAsync(uint from, uint to);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetBy", ReplyAction="ServiceModel/BaseService/GetByResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.DeliveriService))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.OrderedProduct>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.OrderedProduct))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.OrderStatus>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataModelLibrary.OrderStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DataModelLibrary.Order>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ValueTuple<bool, string>))]
        System.Collections.Generic.List<DataModelLibrary.Order> GetBy(string fieldName, object value);
        
        [System.ServiceModel.OperationContractAttribute(Action="ServiceModel/BaseService/GetBy", ReplyAction="ServiceModel/BaseService/GetByResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetByAsync(string fieldName, object value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersServiceChannel : TestService.OrderService.OrdersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceClient : System.ServiceModel.ClientBase<TestService.OrderService.OrdersService>, TestService.OrderService.OrdersService {
        
        public OrdersServiceClient() {
        }
        
        public OrdersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<bool, object> Create(DataModelLibrary.Order parameter) {
            return base.Channel.Create(parameter);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, object>> CreateAsync(DataModelLibrary.Order parameter) {
            return base.Channel.CreateAsync(parameter);
        }
        
        public System.ValueTuple<bool, string> Update(System.Collections.Generic.List<DataModelLibrary.Order> parameters) {
            return base.Channel.Update(parameters);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> UpdateAsync(System.Collections.Generic.List<DataModelLibrary.Order> parameters) {
            return base.Channel.UpdateAsync(parameters);
        }
        
        public System.ValueTuple<bool, string> Delete(System.Collections.Generic.List<DataModelLibrary.Order> parameters) {
            return base.Channel.Delete(parameters);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> DeleteAsync(System.Collections.Generic.List<DataModelLibrary.Order> parameters) {
            return base.Channel.DeleteAsync(parameters);
        }
        
        public System.Collections.Generic.List<DataModelLibrary.Order> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.Collections.Generic.List<DataModelLibrary.Order> GetFromTo(uint from, uint to) {
            return base.Channel.GetFromTo(from, to);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetFromToAsync(uint from, uint to) {
            return base.Channel.GetFromToAsync(from, to);
        }
        
        public System.Collections.Generic.List<DataModelLibrary.Order> GetBy(string fieldName, object value) {
            return base.Channel.GetBy(fieldName, value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DataModelLibrary.Order>> GetByAsync(string fieldName, object value) {
            return base.Channel.GetByAsync(fieldName, value);
        }
    }
}
